name: evosteam.com
favicon: null
layout_spectrum: 0.6445090586785227
typography_spectrum: 0.609328561462462
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b181c'
    - '#676b8a'
    - '#ce8f03'
    - '#dddafd'
    - '#b196af'
  brandStrength: 0.10809328034520149
  lightness: 0.08915203553624451
  saturation: 0.25723163271322846
  rhythmicContrast: 0.6543867683503777
purpose: []
